---
- name: Prepare and deploy The Flask App
  hosts: flask_private
  gather_facts: false
  become: true

  vars_files:
    - group_vars/web/admissionhub.yml
    - group_vars/web/db-vault.yml

  roles:

    - role: gh-action
      tags: gh-action

  

  